
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres13:/var/lib/postgresql/data

  redis:
    image: redis:7.0.15-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  web:
    container_name: web
    build: .
    stdin_open: true
    tty: true
    command: ./bin/rails server -b 0.0.0.0 -p 3000
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://postgres:password@db:5432/myapp_development
      REDIS_URL: redis://redis:6379/1
    ports:
      - '3000:3000'
    volumes:
      - .:/rails
    depends_on:
      - db
      - redis

  test:
    build: .
    command: bash -c "bin/rails db:test:prepare && bundle exec rspec"
    volumes:
      - .:/rails
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: test
      DATABASE_URL: postgresql://postgres:password@db:5432/myapp_test
      REDIS_URL: redis://redis:6379/0

volumes:
    postgres13:
    redis_data: